pub extern "js" fn HTMLCanvasElement::getContext(self : HTMLCanvasElement, contextType : String) -> CanvasRenderingContext2D  = "importObject.HTMLCanvasElement.getContext"

pub extern "js" fn HTMLCanvasElement::set_width(self : HTMLCanvasElement, value : Int) = "importObject.HTMLCanvasElement.set_width"

pub extern "js" fn HTMLCanvasElement::set_height(self : HTMLCanvasElement, value : Int) = "importObject.HTMLCanvasElement.set_height"