///|
pub extern "js" fn TextMetrics::width(self : TextMetrics) -> Double = "importObject.TextMetrics.get_width"

///|
pub extern "js" fn TextMetrics::fontBoundingBoxAscent(
  self : TextMetrics
) -> Double = "importObject.TextMetrics.get_fontBoundingBoxAscent"

///|
pub extern "js" fn TextMetrics::fontBoundingBoxDescent(
  self : TextMetrics
) -> Double = "importObject.TextMetrics.get_fontBoundingBoxDescent"
