///|
pub extern type Any

///|
pub extern type Console

///|
pub extern type HTMLCanvasElement

///|
pub extern type HTMLDivElement

///|
pub extern type HTMLAnchorElement

///|
pub extern type HTMLImageElement

///|
pub extern type Document

///|
pub extern type Window

///|
pub extern type EventTarget

///|
pub extern type Node

///|
pub extern type Element

///|
pub extern type HTMLElement

///|
pub extern type CanvasRenderingContext2D

///|
pub extern type Event

///|
pub extern type MouseEvent

///|
pub extern type KeyboardEvent

///|
pub extern type CSSStyleDeclaration

///|
pub extern type TextMetrics

///|
pub extern type OffscreenCanvas

///|
pub extern type OffscreenCanvasRenderingContext2D
